Repository LIS/lis-pipeline, pull requests merged in 2018-12, with the labels that each got.

#377 html_parser: use junit xmls to create comparison
  linux_pipeline/Jenkinsfile_developer_comparison_validation
  scripts/comparison/html_parser.py
Labels: good first issue

#366 LCOW: Pipeline improvements
  linux_pipeline/Jenkinsfile_container_images
  scripts/lcow/Get-Artifacts.ps1
  scripts/lcow/Prepare-Env.ps1
  scripts/lcow/remote_scripts/run_lkp_tests.sh
Labels: LCOW

#373 watcher-ubuntu-azure: Added container deploy
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
  scripts/ubuntu_azure_kernel/ubuntu_azure_kernel_watcher.sh
Labels: bug

#404 LCOW: Added mail summary for all stages
  scripts/lcow/New-Report.ps1
Labels: enhancement
