Repository LIS/lis-pipeline, pull requests merged in 2018-07, with the labels that each got.

#298 azure_linux_automation: Changed repo to the main one
  Jenkinsfile
  linux_pipeline/Jenkinsfile_upstream_kernel
Labels: good first issue

#296 ubuntu-azure-kernel: Added Jenkins definition for ubuntu azure kernel validation
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  scripts/ubuntu_azure_kernel/get_ubuntu_azure_kernel_version.ps1
Labels: feature

#301 ubuntu-azure-kernel: Changed the html download method
  scripts/ubuntu_azure_kernel/get_ubuntu_azure_kernel_version.ps1
Labels: Important Fix
