Repository LIS/lis-pipeline, pull requests merged in 2018-11, with the labels that each got.

#355 developer and bisect pipelines: Added ubuntu linux-azure tree
  linux_pipeline/Jenkinsfile_developer_comparison_validation
  linux_pipeline/Jenkinsfile_kernel_bisect_controller
Labels: Important Fix

#356 LCOW: Added WSL and LKP testing stages
  linux_pipeline/Jenkinsfile_container_images
  scripts/lcow/Run-LkpTest.ps1
  scripts/lcow/Run-WslTest.ps1
  scripts/lcow/remote_scripts/run_lkp_tests.sh
  scripts/lcow/remote_scripts/run_wsl_tests.sh
Labels: feature

#361 ubuntu-azure-kernel-validation: Refactored the pipeline
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
  scripts/ubuntu_azure_kernel/get_ubuntu_azure_kernel_version.ps1
  scripts/ubuntu_azure_kernel/ubuntu_azure_kernel_watcher.sh
Labels: Important Fix, feature
