Repository LIS/lis-pipeline, pull requests merged in 2018-09, with the labels that each got.

#315 [package_building] Replace `make rpm` with `make rpm-pkg`
  scripts/package_building/build_artifacts.sh
  scripts/package_building_bisect/build_artifacts_bisect.sh
Labels: Important Fix

#316 upstream: Added SRIOV Hyper-V test stage
  linux_pipeline/Jenkinsfile_upstream_kernel
  scripts/lis_hyperv_platform/main_perf.ps1
Labels: enhancement, feature

#323 msft_pipeline: Added jessie functional validation
  Jenkinsfile
Labels: enhancement

#324 lcow: Added kernel watcher and checkbox for pipeline stages
  linux_pipeline/Jenkinsfile_container_images
  scripts/lcow/Copy-Artifacts.ps1
  scripts/lcow/Get-Artifacts.ps1
Labels: Important Fix, feature, good first issue

#332 lcow: Fixed linuxkit stage for RS5
  linux_pipeline/Jenkinsfile_container_images
  scripts/lcow/Build-OpenGCS.ps1
  scripts/lcow/Prepare-Env.ps1
  scripts/lcow/Run-LinuxKit.ps1
  scripts/lcow/Run-StressTest.ps1
Labels: Important Fix, enhancement
