Repository LIS/lis-pipeline, pull requests merged in 2019-06, with the labels that each got.

#485 ubuntu_pipeline: Added Ubuntu 19.04 validation
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  scripts/ubuntu_azure_kernel/ubuntu_azure_kernel_watcher.sh
Labels: enhancement

#488 Fix typo issue
  linux_pipeline/Jenkinsfile_upstream_kernel
Labels: bug

#487 ubuntu_pipeline: Added sign-off stage
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
Labels: enhancement, feature

#489 ubuntu_kernels: add pipeline status reporting
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  scripts/reporting/report_pipeline_status.py
Labels: enhancement

#500 ubuntu_kernel: added stage state reports
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  scripts/reporting/report_pipeline_stage_status.py
Labels: DO_NOT_MERGE, enhancement

#505 Ubuntu Azure Kernel: Trigger stages independently
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
Labels: enhancement

#508 ubuntu_kernel: use kernel type and kernel version for db reports
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
  linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
Labels: DO_NOT_MERGE
